spring.application.name=gamevault
spring.datasource.url=jdbc:postgresql://localhost:5432/gamevault2
spring.datasource.username=postgres
spring.datasource.password=83ythg22hy92eh
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File Upload Limits
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=40MB

# JWT Configuration
# IMPORTANT: In production, use a strong environment variable for the secret
app.jwtSecret=GameVaultSecretKeyForJwtSigningMustBeVeryLongAndSecureGameVaultSecretKeyForJwtSigningMustBeVeryLongAndSecure
app.jwtExpirationInMs=604800000

# File Upload Directory (Relative to project root)
file.upload-dir=uploads